---
services:
  ui:
    image: ghcr.io/serogaq/3x-ui:latest
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    container_name: 3x-ui
    hostname: ${HOSTNAME:-3x-ui}
    networks:
      pubv6:
        ipv6_address: "${V6_ADDRESS}"
      traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.3x-ui.rule=Host(`${XUI_PANEL_DOMAIN}`)"
      - "traefik.http.routers.3x-ui.middlewares=cf-x-real-ip@file"
      - "traefik.http.routers.3x-ui.entrypoints=websecure"
      - "traefik.http.routers.3x-ui.service=3x-ui"
      - "traefik.http.services.3x-ui.loadbalancer.server.port=2053"
      #
      - "traefik.http.routers.3x-ui-sub.rule=Host(`${XUI_SUB_DOMAIN}`)"
      - "traefik.http.routers.3x-ui-sub.middlewares=cf-x-real-ip@file"
      - "traefik.http.routers.3x-ui-sub.entrypoints=websecure"
      - "traefik.http.routers.3x-ui-sub.service=3x-ui-sub"
      - "traefik.http.services.3x-ui-sub.loadbalancer.server.port=2096"
      #
      - "traefik.tcp.routers.vless-reality.rule=HostSNI(`${XUI_VLESS_REALITY_SNI}`) || HostSNI(`www.${XUI_VLESS_REALITY_SNI}`)"
      - "traefik.tcp.routers.vless-reality.tls.passthrough=true"
      - "traefik.tcp.routers.vless-reality.entrypoints=websecure"
      - "traefik.tcp.routers.vless-reality.service=3x-ui-inbound-443"
      - "traefik.tcp.services.3x-ui-inbound-443.loadbalancer.server.port=443"
      - "traefik.tcp.services.3x-ui-inbound-443.loadbalancer.proxyprotocol.version=2"
      #
      - "traefik.tcp.routers.vless-reality-2.rule=HostSNIRegexp(`${XUI_VLESS_REALITY_2_SNI}`)"
      - "traefik.tcp.routers.vless-reality-2.tls.passthrough=true"
      - "traefik.tcp.routers.vless-reality-2.entrypoints=websecure"
      - "traefik.tcp.routers.vless-reality-2.service=3x-ui-inbound-4443"
      - "traefik.tcp.services.3x-ui-inbound-4443.loadbalancer.server.port=4443"
      - "traefik.tcp.services.3x-ui-inbound-4443.loadbalancer.proxyprotocol.version=2"
      #
      - "traefik.tcp.routers.vless-grpc-cloudflare.rule=HostSNI(`${XUI_VLESS_GRPC_SNI}`)"
      - "traefik.tcp.routers.vless-grpc-cloudflare.tls.passthrough=true"
      - "traefik.tcp.routers.vless-grpc-cloudflare.entrypoints=websecure"
      - "traefik.tcp.routers.vless-grpc-cloudflare.service=3x-ui-inbound-8008"
      - "traefik.tcp.services.3x-ui-inbound-8008.loadbalancer.server.port=8008"
      - "traefik.tcp.services.3x-ui-inbound-8008.loadbalancer.proxyprotocol.version=2"
      #
      - "traefik.tcp.routers.vless-ws-gcore.rule=HostSNI(`${XUI_VLESS_WEBSOCKET_SNI}`)"
      - "traefik.tcp.routers.vless-ws-gcore.tls.passthrough=true"
      - "traefik.tcp.routers.vless-ws-gcore.entrypoints=websecure"
      - "traefik.tcp.routers.vless-ws-gcore.service=3x-ui-inbound-8009"
      - "traefik.tcp.services.3x-ui-inbound-8009.loadbalancer.server.port=8009"
      - "traefik.tcp.services.3x-ui-inbound-8009.loadbalancer.proxyprotocol.version=2"
      #
      - "traefik.udp.routers.vless-mkcp-srtp.entrypoints=udp-16384"
      - "traefik.udp.routers.vless-mkcp-srtp.service=3x-ui-inbound-16384"
      - "traefik.udp.services.3x-ui-inbound-16384.loadbalancer.server.port=16384"
      #
      - "traefik.udp.routers.vless-mkcp-dtls.entrypoints=udp-3478"
      - "traefik.udp.routers.vless-mkcp-dtls.service=3x-ui-inbound-3478"
      - "traefik.udp.services.3x-ui-inbound-3478.loadbalancer.server.port=3478"
    volumes:
      - ./db/:/etc/x-ui/
      - ./db/fail2ban.sqlite3:/var/lib/fail2ban/fail2ban.sqlite3
      - ./cert/:/root/cert/
      - ./logs/xray-access.log:/app/access.log
      - ./logs/xray-error.log:/app/error.log
      - ./logs/3xipl.log:/var/log/3xipl.log
      - ./logs/3xipl-ap.log:/var/log/3xipl-ap.log
      - ./logs/3xipl-banned.log:/var/log/3xipl-banned.log
      - ./logs/fail2ban.log:/var/log/fail2ban.log
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Moscow
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_ENABLE_FAIL2BAN: "${XUI_ENABLE_FAIL2BAN:-false}"
      XUI_SERVER_IP: "${XUI_SERVER_IP}"
      XUI_DEBUG: "${XUI_DEBUG:-false}"
      XUI_SOURCE_ROOT: "${XUI_SOURCE_ROOT:-/app/src}"
      XUI_LOG_LEVEL: "${XUI_LOG_LEVEL:-info}"
    tty: true
    restart: unless-stopped
    sysctls:
      - net.ipv4.tcp_fastopen=3
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.default.rp_filter=0
    privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun

networks:
  traefik:
    external: true
  pubv6:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: "${V6_SUBNET}"
          gateway: "${V6_GATEWAY}"